[project]
name = "blowtorch-snn-kernels"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "theguywhoburns", email = "burndev@mail.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "blowtorch-snn",
]

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
blowtorch-snn = { workspace = true }
